name: Recover Keystore

on:
  workflow_dispatch:

jobs:
  recover:
    runs-on: ubuntu-latest
    steps:
      - name: Decode keystore
        run: |
          echo "${{ secrets.YOUR_KEY_SECRET }}" | base64 -d > my.keystore
          sha256sum my.keystore

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: recovered-keystore
          path: my.keystore
          retention-days: 1
